-- RLS 비활성화
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_ai_personalities DISABLE ROW LEVEL SECURITY;
ALTER TABLE emotion_logs DISABLE ROW LEVEL SECURITY; 