name: Daily Emotion Analysis

on:
  schedule:
    # 매일 자정 KST (15:00 UTC)
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next API to run daily emotion analysis (yesterday)
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_URL: ${{ secrets.CRON_API_URL }}
        run: |
          if [ -z "$API_URL" ]; then echo "CRON_API_URL secret missing"; exit 1; fi
          curl -sS -X POST "$API_URL/api/run-daily-emotion-analysis" \
            -H "Content-Type: application/json" \
            -H "x-cron-secret: $CRON_SECRET" \
            -d '{"testToday": false}'
