name: Daily Emotion Analysis

on:
  schedule:
    # 매일 한국시간 자정 (UTC 15:00 = KST 00:00)
    - cron: '0 15 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  daily-emotion-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run daily emotion analysis
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        run: |
          cd server
          npx ts-node src/lib/scheduler.ts
